LMS - SourceCode/LMS.Web/Areas/Admin/Controllers/PlacedCandidateController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using ClosedXML.Excel;
using LMS.Business.Interfaces.Admin;
using LMS.Model.DataViewModel.Admin.PlacedCandidate;
using LMS.Model.DataViewModel.Shared;
using LMS.Utility.Exceptions;
using LMS.Utility.ExtendedMethods;
using LMS.Utility.Helpers;
using LMS.Web.Filters;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;

namespace LMS.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[controller]")]
    [UserAuthentication(Constants.AdminRole)]
    public class PlacedCandidateController : Controller
    {
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IPlacedCandidateHandler placedCandidateHandler;

        public PlacedCandidateController(IHostingEnvironment _hostingEnvironment, IPlacedCandidateHandler _placedCandidateHandler)
        {
            hostingEnvironment = _hostingEnvironment;
            placedCandidateHandler = _placedCandidateHandler;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("[action]")]
        public IActionResult UploadPlacedCandidate(List<IFormFile> files)
        {
            var user = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo) ?? new UserViewModel();
            var msg = string.Empty;
            try
            {
                placedCandidateHandler.UploadFile(user, files);
                ViewData["SuccessMessage"] = "Data Uploaded Successfully";
                msg = "Data Uploaded Successfully";
            }
            catch (XmlFileMapperException ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(PlacedCandidateController), ex);
                ModelState.AddModelError("FileUploadProcessError", ex.Message);
                return View("Index");
            }
            catch (DataNotFound ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(PlacedCandidateController), ex);
                ModelState.AddModelError("FileUploadProcessError", ex.Message);
                return View("Index");
            }
            //ModelState.AddModelError("FileUploadProcessError",msg);
            return View("Index");
        }


        [HttpGet]
        [Route("[action]")]
        public void DownloadTemplate()
        {
            string filePath =
                Path.Combine(hostingEnvironment.WebRootPath, "Templates/PlacedCandidate/PlacedCandidates.xlsx");

            using (var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read))
            {
                HttpContext.Response.ContentType = "application/vnd.ms-excel";

                ContentDispositionHeaderValue contentDisposition =
                    new ContentDispositionHeaderValue("attachment");

                contentDisposition.SetHttpFileName(
                    string.Format("{0}.xlsx", DateTime.Now.Ticks));

                HttpContext.Response.Headers[HeaderNames.ContentDisposition]
                    = contentDisposition.ToString();
                stream.CopyTo(HttpContext.Response.Body);
            }
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult AllPlacedCandidate()
        {
            var user = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo) ?? new UserViewModel();
            IList<PlacedCandidateViewModel> candidate = null;
            try
            {
                candidate = placedCandidateHandler.GetAllCandidate();
            }
            catch (DataNotFound ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(PlacedCandidateController), ex);
            }
            return View();
        }

        [HttpGet]
        [Route("[action]")]
        public JsonResult GetFilteredItems()
        {
            IList<PlacedCandidateViewModel> candidate = new List<PlacedCandidateViewModel>();
            try
            {
                candidate = placedCandidateHandler.GetAllCandidate();
            }
            catch (DataNotFound ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, 0, typeof(PlacedCandidateController), ex);
            }

            int draw = Convert.ToInt32(Request.Query["draw"]);

            int start = Convert.ToInt32(Request.Query["start"]);

            int length = Convert.ToInt32(Request.Query["length"]);

            int sortColumnIdx = Convert.ToInt32(Request.Query["order[0][column]"]);
            string sortColumnName = Request.Query["columns[" + sortColumnIdx + "][name]"];

            string sortColumnDirection = Request.Query["order[0][dir]"];

            string searchValue = Request.Query["search[value]"].FirstOrDefault()?.Trim();

            int recordsFilteredCount =
                    candidate
                    .Where(a => a.CandidateID.Contains(searchValue) || a.CandidateName.Contains(searchValue))
                    .Count();

            int recordsTotalCount = candidate.Count();

            IList<PlacedCandidateViewModel> filteredData = null;
            if (sortColumnDirection == "asc")
            {
                filteredData =
                    candidate
                    .Where(a => a.CandidateID.Contains(searchValue) || a.CandidateName.Contains(searchValue)
                    || a.CandidateEmail.Contains(searchValue) || a.EmployerspocEmail.Contains(searchValue)
                    || a.Castecategory.Contains(searchValue) || a.EducationAttained.Contains(searchValue))
                    .OrderBy(x => x.GetType().GetProperty(sortColumnName)?.GetValue(x))//Sort by sortColumn
                    .Skip(start)
                    .Take(length)
                    .ToList<PlacedCandidateViewModel>();
            }
            else
            {
                filteredData =
                   candidate
                   .Where(a => a.CandidateID.Contains(searchValue) || a.CandidateName.Contains(searchValue)
                    || a.CandidateEmail.Contains(searchValue) || a.EmployerspocEmail.Contains(searchValue)
                    || a.Castecategory.Contains(searchValue) || a.EducationAttained.Contains(searchValue))
                   .OrderByDescending(x => x.GetType().GetProperty(sortColumnName)?.GetValue(x))
                   .Skip(start)
                   .Take(length)
                   .ToList<PlacedCandidateViewModel>();
            }

            return Json(
                        new
                        {
                            data = filteredData,
                            draw = Request.Query["draw"],
                            recordsFiltered = recordsFilteredCount,
                            recordsTotal = recordsTotalCount
                        }
                    );
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult ExportToExcel()
        {
            var user = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo) ?? new UserViewModel();
            try
            {
                DataTable dt = placedCandidateHandler.GetDataInExcel();
                string fileName = "PlacedCandidate.xlsx";
                using (XLWorkbook wb = new XLWorkbook())
                {
                    wb.Worksheets.Add(dt);
                    using (MemoryStream stream = new MemoryStream())
                    {
                        wb.SaveAs(stream);
                        return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
                    }
                }
            }
            catch (DataNotFound ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(PlacedCandidateController), ex);
            }
            return View();
        }


    }
}

LMS - SourceCode/LMS.Web/Areas/Admin/Views/PlacedCandidate/AllPlacedCandidate.cshtml
@*@model IEnumerable<LMS.Model.DataViewModel.Admin.PlacedCandidate.PlacedCandidateViewModel>*@

@{
    ViewData["Title"] = "Hired Candidate";
}
<link href="~/lib/datatable/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/css/Loader.css" rel="stylesheet" />
<style>
    button {
        position: absolute;
    }
</style>
<!-- Page Title start -->
<div class="pageTitle">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h1 class="page-heading">Hired Candidate List</h1>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="breadCrumb"><a href="/Home/Index/">Home</a> / <span>Admin</span></div>
            </div>
        </div>
    </div>
</div>
<!-- Page Title End -->

<div class="container" style="padding-top:20px;padding-bottom:170px;">
    <div class="row">
        <hr />
        <div class="col-md-12 table-responsive">
            <button value="exportexcel" class="btn btn-primary" onclick="location.href='@Url.Action("ExportToExcel","PlacedCandidate")'">Export Data</button>
            <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%" id="dataTable">
                <thead>
                    <tr>
                        <th>CandidateID</th>
                        <th>CandidateName</th>
                        <th>CandidateEmail</th>
                        <th>Castecategory</th>
                        <th>EducationAttained</th>
                        <th>EmployerspocEmail</th>
                        @*<th>Gender</th>
                    <th>EmployerSpocName</th>
                    <th>EmployerType</th>
                    <th>FromDate</th>
                    <th>FYWise</th>*@
                        <th>CreatedDate</th>
                    </tr>
                </thead>
                @*<tbody>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>@user.CandidateEmail</td>
                        <td>@user.CandidateID</td>
                        <td>@user.CandidateName</td>
                        <td>@user.Castecategory</td>
                        <td>@user.EducationAttained</td>
                        <td>@user.EmployerspocEmail</td>
                        <td>@user.Gender</td>
                        <td>@user.EmployerSpocName</td>
                        <td>@user.EmployerType</td>
                        <td>@user.FromDate</td>
                        <td>@user.FYWise</td>
                        <td>@user.CreatedDate</td>
                    </tr>
                }
            </tbody>*@
            </table>
        </div>
    </div>
</div>
<div id="loader" hidden>
    <img id="imgloader" src="~/images/ajax-loader1.gif" />
</div>

<!-- Modal -->


@section Scripts
    {
    <script src="~/lib/datatable/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatable/js/dataTables.bootstrap4.min.js"></script>
    @*<script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>*@
    <script src="~/js/Admin/PlacedCandidate/serversidepaging.js"></script>
}

LMS - SourceCode/LMS.Web/Areas/Admin/Views/PlacedCandidate/Index.cshtml
@{
    ViewData["Title"] = "Upload Candidates";
}
<link href="~/css/fileUploadControl.css" rel="stylesheet" />
<div class="pageTitle">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h1 class="page-heading">Upload Hired Candidates</h1>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="breadCrumb"><a href="/Home/Index/">Home</a> / <span>@ViewData["Title"]</span></div>
            </div>
        </div>
    </div>
</div>

<div class="listpgWraper">
    <div class="col-sm-12">
        <form asp-action="UploadPlacedCandidate" method="post" onsubmit="return uploadCandidate(this)" enctype="multipart/form-data">
            @*@if (!string.IsNullOrWhiteSpace(Convert.ToString(ViewData["SuccessMessage"])))
                {
                    <div class="alert alert-success" style="text-align: center;font-weight: bold;" role="alert">@ViewData["SuccessMessage"]</div>
                }*@
            <div class="col-sm-offset-4 frame">
                @*<h2 class="white">Upload Candidate</h2>*@
                <div class="col-sm-5 center">
                    <div asp-validation-summary="All" style="color:red;font-weight:bold;">
                    </div>
                    @if (!string.IsNullOrWhiteSpace(Convert.ToString(ViewData["SuccessMessage"])))
                    {
                        <label id="success" style="color:green;font-weight:bold;padding-top: 10px;">@ViewData["SuccessMessage"]</label>
                    }

                    <label id="message" asp-validation-summary="" style="color:red;font-weight:bold;padding-top: 10px;"></label>

                    <br />
                    <div class="title">
                        <h5>Drop file to upload</h5>
                        <span class="template-download-link-container">
                            <a asp-action="DownloadTemplate">Download Template</a>
                        </span>

                    </div>
                    <div class="dropzone">
                        <p>Click or drag on bulk upload portion</p>
                        <h1 class="imgupload"><i class="fa fa-file-excel-o"></i></h1>
                        <input type="file" name="files" class="upload-input" onchange="fileSelected(this)" />
                    </div>
                    <label id="fileName" style="font-weight:bold;text-align:center;margin-bottom:5px;margin-top:5px;"></label>

                    <button type="submit" class="UploadFilebtn" name="uploadbutton">Upload file</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts
    {
    <script src="~/js/Admin/PlacedCandidate/placedcandidate.js"></script>
}