LMS - SourceCode/LMS.Web/Areas/Employer/Controllers/SearchResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using LMS.Business.Interfaces.Employer.JobPost;
using LMS.Business.Interfaces.Employer.SearchResume;
using LMS.Business.Interfaces.Home;
using LMS.Business.Interfaces.Jobseeker;
using LMS.Business.Interfaces.Shared;
using LMS.Model.DataViewModel.Employer.SearchResume;
using LMS.Model.DataViewModel.Shared;
using LMS.Utility.Exceptions;
using LMS.Utility.ExtendedMethods;
using LMS.Utility.Helpers;
using LMS.Web.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace LMS.Web.Areas.Employer.Controllers
{
    [Area("Employer")]
    [Route("[controller]")]
    [HandleExceptionsAttribute]
    [UserAuthentication(Constants.CorporateRole + "," + Constants.StaffingPartnerRole)]
    public class SearchResumeController : Controller
    {

        private readonly IJobPostHandler jobpastHandler;
        private readonly IHomeHandler homeHandler;
        private readonly ISearchResumeHandler searchresumehandler;
        private readonly IEMailHandler emailHandler;
        private readonly IConfiguration config;
        public SearchResumeController(IEMailHandler _emailHandler,IConfiguration _config, IJobPostHandler _jobpastHandler, IHomeHandler _homeHandler, ISearchResumeHandler _searchResumeHandler)
        {
            jobpastHandler = _jobpastHandler;
            homeHandler = _homeHandler;
            searchresumehandler = _searchResumeHandler;
            emailHandler = _emailHandler;
            config = _config;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [HttpGet]
        [Route("[action]")]
        public IActionResult SearchResumeList(SearchResumeViewModel searches)
        {
            List<SearchResumeListViewModel> lstResumeList = new List<SearchResumeListViewModel>();
            try
            {
                var user = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo);
                var props = searches.GetType().GetProperties();
                foreach (PropertyInfo prop in props)
                {
                    if (prop.PropertyType.IsArray)
                    {
                        var values = prop.GetValue(searches) as string[];
                        if (null != values)
                        {
                            List<string> finalValues = new List<string>();
                            foreach (var value in values)
                            {
                                if (null != value)
                                {
                                    finalValues.AddRange(value.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries));
                                }
                            }
                            prop.SetValue(searches, finalValues.ToArray());
                        }
                    }
                }
                ViewBag.JobIndustryArea = jobpastHandler.GetJobIndustryAreaWithStudentData();
                ViewBag.City = homeHandler.GetCitiesWithJobSeekerInfo();
                ViewBag.Searches = searches;
                lstResumeList = searchresumehandler.GetSearchResumeList(searches);
            }

            catch (DataNotFound ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, 0, typeof(SearchResumeController), ex);
            }
            return View(lstResumeList);
        }

        [HttpGet]
        [Route("[action]")]
        public IActionResult ShowCandidateDetail(int userId)
        {
            SearchResumeListViewModel listresume = new SearchResumeListViewModel();
            var user = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo);
            user = user ?? new UserViewModel();
            try
            {
                listresume = searchresumehandler.ShowCandidateDetails(user.UserId, userId);
            }
            catch (DataNotFound ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(SearchResumeController), ex);
                //ModelState.AddModelError("ErrorMessage", string.Format("{0}", ex.Message));
            }
            return View(listresume);
        }


        [HttpGet]
        [Route("[action]")]
        public IActionResult SendMessage(string userEmail,string JobSeekerName)
        {
            bool isSend = true;
            string errorMessage;
            var user  = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo) ?? new UserViewModel();
            JobSeekerName = string.IsNullOrWhiteSpace(JobSeekerName) ? "Candidate" : JobSeekerName;
            try
            {
                var eModel = new EmailViewModel
                {
                    Subject = "New Job from Placement Portal",
                    Body = "Dear " + JobSeekerName + ",<br/>Your resume has been shortlisted by " + user.CompanyName + ".<br/>The employer will connect with you for further processing.<br/><br/>Thank You<br/>Placement Portal Team",
                    To = new string[] { userEmail },
                    From = config["EmailCredential:Fromemail"],
                    IsHtml = true,
                    MailType = (int)MailType.NotAllowed
                };
                emailHandler.SendMail(eModel,-1);

                errorMessage = "Your mail has been successfully send to the Jobseeker";
                return Json(new { isSend, errorMessage });
            }
            catch
            {
                ViewData["Error"] = "your mail has not been send";
                isSend = false;
                errorMessage = "mail not send";

            }
            return Json(new { isSend, errorMessage });
        }

    }
}

LMS - SourceCode/LMS.Web/Areas/Jobseeker/Controllers/JobController.cs
using LMS.Business.Interfaces.Employer.JobPost;
using LMS.Business.Interfaces.Home;
using LMS.Business.Interfaces.Jobseeker;
using LMS.Model.DataViewModel.Employer.JobPost;
using LMS.Model.DataViewModel.JobSeeker;
using LMS.Model.DataViewModel.Shared;
using LMS.Utility.Exceptions;
using LMS.Utility.ExtendedMethods;
using LMS.Utility.Helpers;
using LMS.Web.Filters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace LMS.Web.Areas.Jobseeker.Controllers
{
    [Area("Jobseeker")]
    [Route("[controller]")]

    [HandleExceptionsAttribute]
    public class JobController : Controller
    {
        private readonly IUserProfileHandler userProfileHandler;
        private readonly IJobPostHandler jobpastHandler;
        private readonly IHomeHandler homeHandler;
        private readonly ISearchJobHandler searchJobHandler;
        public JobController(IJobPostHandler _jobpastHandler, IHomeHandler _homeHandler, IUserProfileHandler _userProfileHandler, ISearchJobHandler _searchJobHandler)
        {
            jobpastHandler = _jobpastHandler;
            homeHandler = _homeHandler;
            searchJobHandler = _searchJobHandler;
            userProfileHandler = _userProfileHandler;
        }

        public IActionResult Index()
        {
            return View();
        }

        //[HttpGet]
        //[Route("[action]")]
        //public IActionResult SearchJobList([FromQuery]SearchJobViewModel searches)
        //{

        //    return View();
        //}

        [HttpPost]
        [HttpGet]
        [Route("[action]")]
        public IActionResult SearchJobList(SearchJobViewModel searches)
        {
            List<SearchJobListViewModel> lstjobList = new List<SearchJobListViewModel>();
            var user = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo);
            user = user ?? new UserViewModel();
            try
            {
                if (null == user)
                {
                    user = new UserViewModel();
                }
                var props = searches.GetType().GetProperties();
                foreach (PropertyInfo prop in props)
                {
                    if (prop.PropertyType.IsArray)
                    {
                        var values = prop.GetValue(searches) as string[];
                        if (null != values)
                        {
                            List<string> finalValues = new List<string>();
                            foreach (var value in values)
                            {
                                if (null != value)
                                {
                                    finalValues.AddRange(value.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries));
                                }
                            }
                            prop.SetValue(searches, finalValues.ToArray());
                        }
                    }
                }

                ViewBag.JobIndustryArea = jobpastHandler.GetJobIndustryAreaWithJobPost();
                ViewBag.City = homeHandler.GetCityHasJobPostId();
                ViewBag.Company = homeHandler.GetCompanyHasJobPostId();
                ViewBag.Searches = searches;
                lstjobList = searchJobHandler.SearchJobList(searches, user.UserId);
            }

            catch (DataNotFound ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(JobController), ex);
                ModelState.AddModelError("ErrorMessage", string.Format("{0}", ex.Message));
            }
            catch(Exception ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(JobController), ex);
            }
            return View(lstjobList);
        }


        [HttpGet]
        [Route("[action]")]
        //[UserAuthentication(Constants.JobSeekers)]
        public IActionResult ApplyJob(int jobPostId, string currentUrl)
        {
            string applyJobURL = currentUrl;
            HttpContext.Session.Set<string>(Constants.SessionRedirectUrl, applyJobURL);

            var user = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo);
            user = user ?? new UserViewModel();
            string result = "";
            try
            {
                if (user.UserId == 0)
                {
                    result = "Please login to apply this job";
                }

                else if (user.RoleName == "Student")
                {
                    if (userProfileHandler.ApplyJobDetails(user, jobPostId))
                    {
                        result = "Job applied";
                    }
                }
                else
                {
                    result = "Oops! Applicable For Job Seeker Only.";
                }
            }

            catch (FaildToApplyJob ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(JobController), ex);
                result = ex.Message;
                ModelState.AddModelError("ErrorMessage", string.Format("{0}", ex.Message));
            }
            catch (DataNotUpdatedException ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(JobController), ex);
                result = ex.Message;
                ModelState.AddModelError("ErrorMessage", string.Format("{0}", ex.Message));
            }

            catch (AllReadyExistJob ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(JobController), ex);
                result = ex.Message;
                ModelState.AddModelError("ErrorMessage", string.Format("{0}", ex.Message));
            }
            catch (System.Net.Mail.SmtpFailedRecipientException ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(JobController), ex);
                result = "Job applied";
                ModelState.AddModelError("ErrorMessage", string.Format("{0}", ex.Message));
            }
            return Json(result);
        }


        [HttpGet]
        [Route("[action]")]
        //[UserAuthentication(Constants.AllRoles)]
        public IActionResult JobDetails(int jobid)
        {
            JobPostViewModel jobdetail = new JobPostViewModel();
            var user = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo);
            user = user ?? new UserViewModel();
            try
            {
                jobdetail = jobpastHandler.GetJobDetails(jobid);
                //string imgname = Path.GetFileName(jobdetail.CompanyLogo);
                //jobdetail.CompanyLogo = $@"/ProfilePic/" + imgname;
                if (user != null)
                {
                    List<int> appliedjobs = homeHandler.GetAplliedJobs(user.UserId);
                    //if(jobid == appliedjobs.)
                    for (int i = 0; i < appliedjobs.Count; i++)
                    {
                        //getting the all the jobs applied by user only if the user logged in
                        if (appliedjobs[i] == jobid)
                        {
                            jobdetail.IsApplied = true;
                            break;
                        }
                    }
                }

            }
            catch (DataNotFound ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(JobController), ex);
                //result = ex.Message;
                ModelState.AddModelError("ErrorMessage", string.Format("{0}", ex.Message));
            }
            return View(jobdetail);
        }

        [HttpGet]
        [Route("[action]")]
        [UserAuthentication(Constants.JobSeekers)]
        public IActionResult RecommendedJobs()
        {
            List<SearchJobListViewModel> list = new List<SearchJobListViewModel>();
            var user = HttpContext.Session.Get<UserViewModel>(Constants.SessionKeyUserInfo);
            user = user ?? new UserViewModel();
            try
            {
                //list = jobpastHandler.RecommendedJobs(user.SSCJobRoleId);
                if (user != null)
                {
                    List<int> appliedjobs = homeHandler.GetAplliedJobs(user.UserId);
                    for (int i = 0; i < appliedjobs.Count; i++)
                    {
                        list[i].IsApplied = appliedjobs.Any(aj => aj == list[i].JobPostId);
                    }                    
                }
            }
            catch (DataNotFound ex)
            {
                Logger.Logger.WriteLog(Logger.Logtype.Error, ex.Message, user.UserId, typeof(JobController), ex);
                ModelState.AddModelError("ErrorMessage", string.Format("{0}", ex.Message));
            }
            return View(list);
        }
    }
}

LMS - SourceCode/LMS.Web/Views/Shared/EmailPromptPartial.cshtml
@model EmailViewModel
<style>
    .labelspace {
        margin-bottom: 0.7rem;
        font-weight: bold;
    }
</style>
<div class="row">
    <div class="col-md-12">
        <form>
            <input type="hidden" name="MessageId" value="@ViewBag.MessageId" />
            <input type="hidden" name="SenderId" value="@ViewBag.SenderId" />
            <input type="hidden" name="ReceiverId" value="@ViewBag.ReceiverId" />
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="txtFrom" class="labelspace">From</label>
                </div>
                <div class="col-md-12">
                    <input type="text" readonly class=" form-control" name="SenderEmail" value="@Model.From" id="txtFrom" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="txtTo"  class="labelspace">To</label>
                </div>
                <div class="col-md-12">
                    <input type="text" readonly class=" form-control" name="ReceiverEmail" value="@(string.Join(',',Model.To))" id="txtTo" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="txtSubject"  class="labelspace">Subject</label>
                </div>
                <div class="col-md-12">
                    <input type="text" class=" form-control" name="Subject" value="@Model.Subject" id="txtSubject" required/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-12">
                    <label for="txtBody"  class="labelspace">Body</label>
                </div>
                <div class="col-md-12">
                    <textarea id="txtBody" rows="8" cols="30" maxlength="600"
                              class="form-control ckeditor" name="Body" required></textarea>
                    @*<input type="text" class=" form-control" name="Body" value="@Model.Body" id="txtBody" />*@
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    CKEDITOR.replace('txtBody');
</script>

LMS - SourceCode/LMS.Web/Views/Shared/SearchJobPartial.cshtml
@using LMS.Model.DataViewModel.Shared
@model SearchJobViewModel

<div>
    @{
        UserViewModel user = Context.Session.Get<UserViewModel>
    (Constants.SessionKeyUserInfo);
        int jRoleId = 0;
        string jRole = string.Empty;
        if (null != user)
        {            
            jRole = user.JobTitleName;
        }


        <form asp-area="Jobseeker" id="formJobPartial" asp-controller="Job" asp-action="SearchJobList" method="post">
            <div class="col-md-3">
                @*<input type="hidden" asp-for="JobRole" value="@jRoleId" id="hiddenjobtitle" />*@
                <select type="text" asp-for="JobTitle" id="jobtitle" multiple asp-items="@(new SelectList(ViewBag.AllJobRoles,"JobTitleId","JobTitleName"))" autocomplete="off" class="form-control chosen-select" data-placeholder="Choose Job Title"></select>
            </div>
            <div class="col-md-2 autocomplete">
                <input type="text" asp-for="Skills" class="form-control" placeholder="Skill" />
            </div>
           
            <div class="col-md-2">
                @if (ViewBag.JobIndustryArea != null)
                {
                    <select asp-for="JobCategory[0]" class="form-control" asp-items="@(new SelectList(@ViewBag.JobIndustryArea,"JobIndustryAreaId", "JobIndustryAreaName"))">
                        <option value="">Job Category</option>
                    </select>
                }
                else
                {
                    <select asp-for="JobCategory" class="form-control" >
                        <option value="">Job Category</option>
                    </select>
                }
            </div>
            <div class="col-md-1">
                <select class="form-control" asp-for="Experiance">
                    <option value="-1">Year</option>
                    <option value="0">Fresher</option>
                    @for (int i = 1; i <= 15; i++)
                    {
                        <option value=@i>@(i)</option>

                    }
                </select>
            </div>
            <div class="col-md-2 autocomplete">
                <input asp-for="City" type="hidden" id="hdnCity" />
                <input type="text" id="City" class="form-control" placeholder="Enter city" />
            </div>
            <div class="col-md-2">
                <input type="submit" id="SearchJobPartial" class="btn" value="Search Job">
            </div>
        </form>
    }
</div>

LMS - SourceCode/LMS.Web/Views/Shared/SearchResumePartial.cshtml
@using LMS.Model.DataViewModel.Shared
@model SearchResumeViewModel
<style>
    .multiselect-selected-text {
        height: 50px !important;
        border-radius: 0 !important;
        /* padding: 0px 0px; */
        border: none !important;
        font-size: 18px !important;
        margin-top: -4px;
    }
</style>
<div>
    <form asp-area="Employer" asp-controller="SearchResume" asp-action="SearchResumeList" method="post">
        @*<div class="col-md-2">
            <input type="text" asp-for="Skills" class="form-control" placeholder="Enter Skills" />
        </div>*@
        @*<div class="col-md-2">
            <select asp-for="JobCategory[0]" class="form-control" asp-items="@(new SelectList(@ViewBag.JobIndustryArea,"JobIndustryAreaId", "JobIndustryAreaName"))">
                <option value="">Job Category</option>
            </select>
        </div>*@
        <div class="col-md-4">
            @*<input type="hidden" id="hdnJobRoleIds" asp-for="JobRoles"/>
            <select class="form-control" multiple="multiple" asp-items="@(new SelectList( ViewBag.AllJobRoles, "JobTitleId", "JobTitleName"))" id="ddlJobRoles"></select>*@
            
            <input type="text" class="form-control" asp-for="Skills" placeholder="Enter a skill">

        </div>
        <div class="col-md-2">
            <select class="form-control" title="Min Exp" name="minExp" asp-for="MinExp">
                <option value="-1">Min Exp</option>
                <option value="0">Fresher</option>
                @for (int i = 1; i <= 15; i++)
                {
                    <option value=@i>@(i) Year(s)</option>

                }
            </select>
        </div>
        <div class="col-md-2">
            <select class="form-control" title="Max Exp" name="maxExp" asp-for="MaxExp">
                <option value="-1">Max Exp</option>
                <option value="0">Fresher</option>
                @for (int i = 1; i <= 15; i++)
                {
                    <option value=@i>@(i) Year(s)</option>

                }
            </select>
        </div>
        <div class="col-md-2 autocomplete">
            <input asp-for="City" type="hidden" id="hdnCity" />
            <input type="text" id="City" class="form-control" placeholder="Enter city" />
        </div>
        <div class="col-md-2">
            <input type="submit" class="btn" value="Search Resume">
        </div>
    </form>
</div>